import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import NavBar from '@/components/NavBar';
import ToasterProvider from '@/lib/ToasterProvider';
import Footer from '@/components/Footer';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Adarsh Store',
    description: 'Generated by Adarsh with store app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ClerkProvider>
                    <NavBar />
                    {children}
                    <Footer />
                    <ToasterProvider />
                </ClerkProvider>
            </body>
        </html>
    );
}
