import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import NavBar from '@/components/NavBar';
import ToasterProvider from '@/lib/ToasterProvider';
import Footer from '@/components/Footer';
import '../globals.css';
import 'react-loading-skeleton/dist/skeleton.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'E-Shopify Store',
    description: 'Generated by Adarsh with store app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Suspense fallback={<>Loading...</>}>
                    <ClerkProvider>
                        <NavBar />
                        {children}
                        <Footer />
                        <ToasterProvider />
                    </ClerkProvider>
                </Suspense>
            </body>
        </html>
    );
}
